services:
  - type: web
    name: dyen-web
    env: docker
    repo: https://github.com/e1994966/dyen.git
    branch: main
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
          name: dyen-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: dyen-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: dyen-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: dyen-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: dyen-db
          property: password

databases:
  - name: dyen-db
    plan: free
    databaseName: dyen
