services:
  - type: web
    name: dyen-web
    env: docker
    repo: https://github.com/e1994966/dyen.git
    branch: main
    dockerfilePath: Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: APP_DEBUG
        value: true
      - key: LOG_CHANNEL
        value: stack
